language: python
python:
  - '3.5'
sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.21.2
  COMPOSE_FILE: tests/docker-compose.yml

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - pip install -U -r  tests/requirements.txt

script:
  - docker-compose -f $COMPOSE_FILE build
  - pytest --docker-compose-file=$COMPOSE_FILE -vvv

after_script:
  - docker-compose -f $COMPOSE_FILE down

deploy:
  on:
    branch: master
    tags: true
  provider: script
  script: .travis/docker_push.sh
